### PR TITLE
fix evap units and sign

### LINKED ISSUE #727: fix units and sign for evap passed to coupler CESM driver
Currently we are converting `evap` to m by multiplying by `MM_PER_M`, which is not necessary to convert mm to kg m2/s, before we pass it to the coupler in the CESM driver. We're also multiplying by a negative sign. Neither of these are necessary - we just need to divide by `global_param.dt`.

### PR DESCRIPTION
**Pull request by dgergel**
- [X] closes #727 
- [X] tests passed
- [X] new tests added
- [X] science test figures
- [X] ran uncrustify prior to final commit
- [X] ReleaseNotes entry

### CODE REVIEW

**Comment by bartnijssen** [comment]
Which #xxx is this closing (the point is to indicate which issue this PR is related to)?

File: vic/drivers/cesm/src/cesm_put_data.c [hunk 1]
```diff
@@ -159,9 +159,8 @@ vic_cesm_put_data()
 
         // evaporation, VIC: mm, CESM: kg m-2 s-1
         // TO-DO should we incorporate bare soil evap?
```
Comment (bartnijssen) [inline vic/drivers/cesm/src/cesm_put_data.c]: Is this TODO still relevant? My assumption is that WRF wants total evap, so if soil evap is already included in `OUT_EVAP` then we should be OK. If not, then we should add it.

Comment (dgergel) [inline vic/drivers/cesm/src/cesm_put_data.c]: It's not still relevant. Since we're using `evap` from `OUT_DATA` here, it's already incorporating soil evap.

**Comment by dgergel** [comment]
@bartnijssen I hadn't opened an issue. Will do that so that we can close it with this PR.
